脏数据类型有：丢失数据，重复数据，不一致数据，无效和错误数据、

第三范式：每列是同一个变量，每行为一组完整观测值，每个单元格是一个有效值

### 提取dataframe部分行：

`df1.head(10)` 提取df前10行

`df1.tail(4)` 提取df后四行

`df1.sample(7)` 随机提取df中任意7行

### 调整单元格展示：

`pd.set_option('display.max_columns',150)`调整展示出150行

`pd.set_option('display.max_colwidth',500)` 调整展示单元格字符上限为500

### 重复数据的处理：duplicated方法

`df['列名'].duplicated()`

若当前值为非重复值(在同一表中之前未出现过的值)，返回False(第一次出现)

若当前值为重复值，则返回True

`df.duplicated(subset=['列名1','列名2'])`

只有subset内所有列数值都相同时，才会返回True

提取重复数据示例：

`students[students.duplicated(subset=['学号','姓别'])]`

### 评估不一致数据：

`students['列名称'].value_counts()` 统计某列元素名称及元素个数

`students['列名'].sort_values()` # 首先对某一列数值进行排序，因此得到可能存在不一致的极大极小值

### 重命名dataframe的索引和列名：

索引：`df.rename(index={字典})`

列名：`df.rename(columns={字典})`

字典：将老的index或column作为键，新的index(column)作为value，即:老的值作为键，新值作为value

注意：此时并未更改原始df，需要为其重新赋值


通过在rename()内部添加`inplace=True`，可以直接将新的df赋值给原始df，如:

`df.rename(index={字典},inplace=True)`

`df.rename(columns={字典},inplace=True)`

### 在rename内部也可以直接传入函数或方法，如：

`df.rename(index=函数名或方法名)`

`df.rename(columns=str.upper)` 所有列名称变为大写

### 指定某列作为索引:

`df1.set_index('列名称')`

### 重置索引:重新以001，002作为索引（恢复为默认索引方法）

`df1.reset_index('列名称')`

### 对索引重新排序:

`df1.sort_index(inplace=True)`

### 对列名进行排序:

`df.sort_index(axis=1)`

### 整洁数据:

第三范式：每列是同一个变量，每行为一组完整观测值，每个单元格是一个有效值

数据转置：(行列互换)

`df1=df1.T`

### 对列进行拆分:split方法

`df1['新列名称1','新列名称2']=df1['要拆分的列'].str.split('/',expand=True)`

用/作为分隔符，expand=True表示把分割后的列分表单独保存

然后通过drop方法删除原始列:

`df1.drop['要删除的列名',axis=1]`

### 把不同的列合并：str.cat方法

如：合并‘姓’这一列和‘名’这一列为‘姓名’列

`df1['姓'].str.cat(df1['名']sep='')`

sep=''内部传入指定拼接时的分隔符，如-_等等

### 宽数据转化为长数据：pd.melt()方法

`df1=pd.melt(df1,id_vars=['',''],var_name='',value_name='')`

df1=pd.melt(要转化的列表名，不进行转化操作的列名，转化后包含原本列的新列的名，转化后包含原本变量值的新的列名)

### 对行进行拆分：explode方法

`df.explode('要拆分的列名')`

### 对行列进行删除：drop方法

`df1=df1.drop(['',''],axis= )`

drop()括号内部可以传入列表，以此来同时删除多行或多列

当axis=1表示删除行，=0表示默认情况下，此时删除列

### 对整列缺失值处理      

对整列所有数据统一赋值(类似于广播机制)

`df1['列名']='value'`

对某一指定值赋值：

`df1.loc['行名称','列名称']='value'`

`df1.iloc['行index','列index']='value'`

对某一区域赋值：

`df1.loc['行名称':'行名称','列名称':'列名称']=[value,value,....value]`

`df1.iloc['行index':'行index','列index':'列index']=[value,value,....value]`

支持切片同时为多项赋值

### 程序自动查找NaN值：fillna方法
为df1中所有NaN值赋值为0

`df1.fillna(0)`

为df1中某一指定列所有NaN值赋值为0

`df1['列名'].fillna(0)`

某一指定列以平均值代替NaN

`df1['列名'].fillna(.df1['列名'].mean())`

通过传入字典为多个不同列的NaN元素赋不同的值(如：把a列赋值为10,b列赋值21，c列赋值9)

`df1.fillna({'a':10,'b':21,'c':9})`

##### fillna方法不改变原始df，而是会传到一个新的df，因此需要对原始df重新赋值，或者传入inplace=True参数 例：

`df1.fillna(0,inplace=True)`

### 删除有缺失值的数据：dropna方法

只返回没有NaN行的数据：(任意行观测值中只要有一个参数为NaN，该行就会被删掉，必须该行所有的参数全为非NaN值，该行才会被保留)

`df1.dropna()`

只对某一(些)指定列进行检查，若这一(些)列中含有NaN值，则删除这列对应的整行观测值

`df1.dropna(subset=['列名','列名','列名'])`

##### dropna方法不改变原始df，而是会传到一个新的df，因此需要对原始df重新赋值，或者传入inplace=True参数 例：

`df1.dropna(subset=['列名','列名','列名']，inplace=True)`

### 删除重复数据(行)：drop_duplicates方法

当某行元素与之前某行元素完全相同时，后出现的行将会被删除

`df1.drop_duplicates()`

只检查subset列表内部的列，若subset列表内部列内元素完全一致，则删除后出现的行，并覆盖原有的行

`df1.drop_duplicates(subset=['列名','列名','列名'],keep=last,inplace=True)`

`inplace=True`表示覆盖原始表格，直接将修改后的表格返还给原表格

`keep=last`表示保留最后一次出现的重复值，而删除之前出现的值

### 对值进行替换(更新)：replace方法

`df1['某一列名'].replace([要修改的元素名],修改后的元素名)`

要修改的元素处可以传入一个参数，或者多个参数组成的列表，例：

`df1['学校'].replace('清华'，'清华大学')`

将'学校'列的所有值为清华的元素修改为清华大学

`df1['学校'].replace(['清华','五道口职业技术学院','TsingHua','青花']，'清华大学')`

将列表内所有元素转为清华大学

##### 还可以通过传入字典的方式，同时修改多个值

`replace_dict={'华南':'华南理工大学','清华':'清华大学','北大':'北京大学','复旦':'复旦大学','陶大':'陶瓷大学'}`
`df1.replace(replace_dict,inplace=True)`

### 对值类型进行转化：astype方法

df1['列名'].astype(要转化后的数据类型)

如：`s1.astype(int)`#将s1转化为int数值类型

##### python里str数值类型等价于jupyter里的object数值类型

##### category数值类型(pandas库内独有的数值类型，记得提前import pandas as pd)

`s2.astype('category')`#记得加引号